base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: hkust-nlp/deita-10k-v0
    type: sharegpt


test_datasets:
  - path: hkust-nlp/deita-quality-scorer-data
    type: completion
    split: validation

dataset_prepared_path: last_run_prepared
output_dir: ./out

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

wandb_project: data-quality-model
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 512
micro_batch_size: 1
num_epochs: 6
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

save_total_limit: 10
warmup_ratio: 0.1
eval_steps: 50
save_steps: 100
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>